baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Skurrilum'
theme = ''

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false

[languages]

[languages.de]
languageName = "Deutsch"
weight = 1
[[languages.de.menu.main]]
  identifier = "menu_home"
  url = "/"
  weight = 1
[[languages.de.menu.main]]
  identifier = "menu_rooms"
  url = "/rooms/"
  weight = 2
[[languages.de.menu.main]]
  identifier = "menu_groups"
  url = "/firmen/"
  weight = 4
[[languages.de.menu.main]]
  identifier = "menu_contact"
  url = "/kontakt/"
  weight = 5
[[languages.de.menu.main]]
  identifier = "menu_faq"
  url = "/faq/"
  weight = 5
[[languages.de.menu.main]]
  identifier = "menu_makers"
  url = "/die-macher/"
  weight = 5

[languages.en]
languageName = "English"
weight = 2
[[languages.en.menu.main]]
  identifier = "menu_home"
  url = "/"
  weight = 1
[[languages.en.menu.main]]
  identifier = "menu_rooms"
  url = "/rooms/"
  weight = 2
[[languages.en.menu.main]]
  identifier = "menu_groups"
  url = "/groups-companies/"
  weight = 4
[[languages.en.menu.main]]
  identifier = "menu_contact"
  url = "/contact/"
  weight = 5
[[languages.en.menu.main]]
  identifier = "menu_faq"
  url = "/fqa/"
  weight = 5
[[languages.en.menu.main]]
  identifier = "menu_makers"
  url = "/the-makers/"
  weight = 5
