baseURL = 'https://staging.seefalke.info/'
languageCode = 'en-us'
title = 'Skurrilum'

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false

[languages]

[languages.de]
languageName = "Deutsch"
weight = 1
[[languages.de.menu.main]]
  identifier = "menu_home"
  name = "Home"
  url = "/"
  weight = 1
[[languages.de.menu.main]]
  identifier = "menu_rooms"
  name = "Unsere Räume"
  weight = 2
[[languages.de.menu.main]]
  identifier = "der-zoo-des-todes-de"
  name = "Der Zoo Des Todes"
  url = "/der-zoo-des-todes/"
  parent = "menu_rooms"
  weight = 1
[[languages.de.menu.main]]
  identifier = "die-phantominsel-de"
  name = "Die Phantominsel"
  url = "/die-phantominsel/"
  parent = "menu_rooms"
  weight = 2
[[languages.de.menu.main]]
  identifier = "die-weinende-frau-de"
  name = "Die Weinende Frau"
  url = "/die-weinende-frau/"
  parent = "menu_rooms"
  weight = 3
[[languages.de.menu.main]]
  identifier = "guschis-geile-grotte-de"
  name = "Guschis Geile Grotte"
  url = "/guschis-geile-grotte/"
  parent = "menu_rooms"
  weight = 4
[[languages.de.menu.main]]
  identifier = "malvinis-vermaechtnis-de"
  name = "Malvinis Vermaechtnis"
  url = "/malvinis-vermaechtnis/"
  parent = "menu_rooms"
  weight = 5
[[languages.de.menu.main]]
  identifier = "menu_groups"
  name = "Firmen"
  url = "/firmen/"
  weight = 3
[[languages.de.menu.main]]
  identifier = "menu_contact"
  name = "Kontakt"
  url = "/kontakt/"
  weight = 4
[[languages.de.menu.main]]
  identifier = "menu_faq"
  name = "FAQ"
  url = "/faq/"
  weight = 5
[[languages.de.menu.main]]
  identifier = "menu_makers"
  name = "Die Macher"
  url = "/die-macher/"
  weight = 6

[languages.en]
languageName = "English"
weight = 2
[[languages.en.menu.main]]
  identifier = "menu_home"
  name = "Home"
  url = "/en/"
  weight = 1
[[languages.en.menu.main]]
  identifier = "menu_rooms"
  name = "Our rooms"
  weight = 2
[[languages.en.menu.main]]
  identifier = "der-zoo-des-todes-en"
  name = "The Zoo Of Death"
  url = "/en/rooms/der-zoo-des-todes/"
  parent = "menu_rooms"
  weight = 1
[[languages.en.menu.main]]
  identifier = "die-phantominsel-en"
  name = "The Phantom Island"
  url = "/en/rooms/die-phantominsel/"
  parent = "menu_rooms"
  weight = 2
[[languages.en.menu.main]]
  identifier = "die-weinende-frau-en"
  name = "The Weeping Woman"
  url = "/en/rooms/die-weinende-frau/"
  parent = "menu_rooms"
  weight = 3
[[languages.en.menu.main]]
  identifier = "guschis-geile-grotte-en"
  name = "Guschi's Seedy Cellar"
  url = "/en/rooms/guschis-geile-grotte/"
  parent = "menu_rooms"
  weight = 4
[[languages.en.menu.main]]
  identifier = "malvinis-vermaechtnis-en"
  name = "Malvini's Legacy"
  url = "/en/rooms/malvinis-vermaechtnis/"
  parent = "menu_rooms"
  weight = 5
[[languages.en.menu.main]]
  identifier = "menu_groups"
  name = "Companies"
  url = "/en/groups-companies/"
  weight = 3
[[languages.en.menu.main]]
  identifier = "menu_contact"
  name = "Contact"
  url = "/en/contact/"
  weight = 4
[[languages.en.menu.main]]
  identifier = "menu_faq"
  name = "FAQ"
  url = "/en/faq/"
  weight = 5
[[languages.en.menu.main]]
  identifier = "menu_makers"
  name = "The Makers"
  url = "/en/the-makers/"
  weight = 6
