name: Build and Deploy Hugo Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true by default in actions/checkout@v2)
          fetch-depth: 0    # Fetch all history for .GitInfo and lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.127.0' # Specify your Hugo version
          extended: true

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.SSH_USER }} # Change this to your VPS username
          VPS_HOST: ${{ secrets.SSH_HOST }} # Change this to your VPS IP or domain
          VPS_DEPLOY_PATH: ${{ secrets.WORK_DIR }} # Change this to the path where you want to deploy on your VPS
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          rsync -avz --delete -e "ssh -i private_key -o StrictHostKeyChecking=no" ./public/ $VPS_USER@$VPS_HOST:$VPS_DEPLOY_PATH
          rm private_key
