
name: Build and Deploy Hugo Project

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive   # for theme submodules
          fetch-depth: 0

      # Install Hugo (extended) — latest stable
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # If using Hugo Modules, ensure Go is available
      - name: Set up Go (for Hugo Modules)
        if: hashFiles('**/go.mod') != ''
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # Build Hugo site -> ./public
      - name: Build the site
        env:
          HUGO_ENV: production
        run: hugo --minify --gc --cleanDestinationDir

      # Deploy to VPS with rsync
      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.SSH_USER }}
          VPS_HOST: ${{ secrets.SSH_HOST }}
          VPS_DEPLOY_PATH: ${{ secrets.WORK_DIR }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          rsync -az --delete -e "ssh -i private_key -o StrictHostKeyChecking=no" ./public/ "$VPS_USER@$VPS_HOST:$VPS_DEPLOY_PATH"
          rm -f private_key
